apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  namespace: cicd-demo
  labels:
    app.kubernetes.io/name: cicd-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cicd-demo
  ports:
    - name: http
      port: 80
      targetPort: http
